src/main/webapp/book/my-review.jsp
src/main/webapp/book/review-upload.jsp
src/main/webapp/common/index.jsp
src/main/webapp/css/header.css
src/main/webapp/css/index.css
src/main/webapp/css/my-review.css
src/main/webapp/css/reivew-upload.css

- 화면 구현 완료
- 검색 페이지의 검색버트는 추후에 조정

랜딩페이지, 독후감 검색 페이지, 독후감 등록 페이지 화면 구현 완료

---

src/main/java/com/livre/model/dao/SuperDao.java

접속개체 url 192.168.0.47:1521:xe 변경

접속개체 url 192.168.0.47:1521:xe 변경

---

src/main/webapp/book/bookCalender.jsp
src/main/webapp/book/main-page.jsp
src/main/webapp/book/my-page.jsp
src/main/webapp/common/start-here.jsp
src/main/webapp/css/bookcalender.css
src/main/webapp/css/main-page.css

2024-02-06

---

src/main/java/com/livre/controller/book/MyReviewController.java
src/main/java/com/livre/model/bean/MyReview.java
src/main/java/com/livre/model/dao/MyBookDao.java
src/main/webapp/book/my-review.jsp
src/main/webapp/css/index.css
src/main/webapp/css/my-review.css

- Review VO 삭제
- 내 독후감 최신순 정렬 수정

내 독후감 최신순 정렬 수정

---

src/main/webapp/book/main-page.jsp
src/main/webapp/book/my-page.jsp
src/main/webapp/common/common-nonbootstrap.jsp
src/main/webapp/css/my-page.css

2024 02 07 JHK- 메인.

---

src/main/java/com/livre/controller/book/MyReviewSearchedController.java
src/main/java/com/livre/model/dao/BookDao.java
src/main/java/com/livre/model/dao/MyReviewDao.java
src/main/java/com/livre/model/dao/SuperDao.java
src/main/java/com/livre/utility/Paging.java
src/main/webapp/WEB-INF/todolist.txt
src/main/webapp/book/my-review-search.jsp
src/main/webapp/common/common.jsp

내 독후감 검색 기능 구현

---

src/main/java/com/livre/controller/member/MemberInsertController.java
src/main/java/com/livre/model/dao/MemberDao.java
src/main/webapp/css/collectPreferenceFirstStyle.css
src/main/webapp/css/collectPreferenceSecondStyle.css
src/main/webapp/css/selectGenderStyle.css
src/main/webapp/js/agreementScript.js
src/main/webapp/js/collectPreferenceFirstScript.js
src/main/webapp/js/collectPreferenceSecondScript.js
src/main/webapp/js/createNicknameScript.js
src/main/webapp/js/finalCheckScript.js
src/main/webapp/js/joinMemberShipScript.js
src/main/webapp/js/selectGenderScript.js
src/main/webapp/member/agreement.jsp
src/main/webapp/member/celebrate.jsp
src/main/webapp/member/collectPreferenceFisrst.jsp
src/main/webapp/member/collectPreferenceSecond.jsp
src/main/webapp/member/createNickname.jsp
src/main/webapp/member/finalCheck.jsp
src/main/webapp/member/joinMemberShip.jsp
src/main/webapp/member/selectGender.jsp

회원가입 내용 일부 수정, 체크박스 작업 등

---

src/main/java/com/livre/controller/book/MyReviewController.java
src/main/java/com/livre/controller/book/MyReviewDetailController.java
src/main/java/com/livre/model/dao/MyReviewDao.java
src/main/webapp/WEB-INF/todolist.txt
src/main/webapp/book/my-review.jsp
src/main/webapp/book/review-upload.jsp
src/main/webapp/css/reivew-upload.css
src/main/webapp/js/myReview.js
src/main/webapp/js/review-upload.js

- 상세보기 가능(장르 이름, 별점 제외)
- 수정하기 활성화 가능(비활성화는 안됨)

상세보기 가능 / 수정하기 활성화 가능

---

src/main/webapp/js/agreementScript.js
src/main/webapp/js/collectPreferenceFirstScript.js
src/main/webapp/js/collectPreferenceSecondScript.js
src/main/webapp/js/createNicknameScript.js
src/main/webapp/js/finalCheckScript.js
src/main/webapp/js/joinMemberShipScript.js
src/main/webapp/js/selectGenderScript.js
src/main/webapp/member/agreement.jsp
src/main/webapp/member/celebrate.jsp
src/main/webapp/member/collectPreferenceFisrst.jsp
src/main/webapp/member/collectPreferenceSecond.jsp
src/main/webapp/member/createNickname.jsp
src/main/webapp/member/finalCheck.jsp
src/main/webapp/member/joinMemberShip.jsp
src/main/webapp/member/selectGender.jsp

선호 장르 최소개수 제한 삭제, 최대 선택 개수 제한 해제, 성별 필수 여부 해제, 닉네임 랜덤 생성 기능(새로고침 시 다른 랜덤닉네임), 축하페이지 홈으로 링크 달아놓음(임시로 index로 이동)

선호 장르 최소개수 제한 삭제, 최대 선택 개수 제한 해제, 성별 필수 여부 해제, 닉네임 랜덤 생성 기능(새로고침 시 다른 랜덤닉네임), 축하페이지 홈으로 링크 달아놓음(임시로 index로 이동)

---

src/main/java/com/livre/controller/member/MemberInsertController.java
src/main/java/com/livre/model/dao/MemberDao.java
src/main/webapp/css/collectPreferenceFirstStyle.css
src/main/webapp/js/agreementScript.js
src/main/webapp/js/collectPreferenceFirstScript.js
src/main/webapp/js/createNicknameScript.js
src/main/webapp/member/agreement.jsp
src/main/webapp/member/collectPreferenceFisrst.jsp
src/main/webapp/member/createNickname.jsp
src/main/webapp/member/meInsertTo.jsp

상세정보 기입 첫 번째 창에 건너뛰기 버튼 추가(클릭 시 바로 축하 페이지로 이동), 약관동의 체크박스 중 하나라도 체크 해제되면

상세정보 기입 첫 번째 창에 건너뛰기 버튼 추가(클릭 시 바로 축하 페이지로 이동), 약관동의 체크박스 중 하나라도 체크 해제되면

---

src/main/java/com/livre/controller/book/InsertReviewController.java
src/main/java/com/livre/controller/book/MyReviewDetailController.java
src/main/java/com/livre/controller/book/MyReviewUpdateController.java
src/main/java/com/livre/model/dao/MyReviewDao.java
src/main/webapp/WEB-INF/todolist.txt
src/main/webapp/book/review-detail-to.jsp
src/main/webapp/book/review-detail.jsp
src/main/webapp/book/review-upload-to.jsp
src/main/webapp/css/reivew-detail.css

독후감 등록 기능 일부 구현

---

src/main/java/com/livre/controller/member/MemberInsertController.java
src/main/java/com/livre/model/bean/Member.java
src/main/java/com/livre/model/dao/MemberDao.java
src/main/webapp/js/agreementScript.js
src/main/webapp/js/joinMemberShipScript.js
src/main/webapp/member/agreement.jsp
src/main/webapp/member/celebrate.jsp
src/main/webapp/member/collectPreferenceFisrst.jsp
src/main/webapp/member/joinMemberShip.jsp
src/main/webapp/member/meInsertTo.jsp

선 약관동의 후 이메일/비번 입력, 파라미터 term_FL이름 변경(sql과 일치화), DB데이터 들어가는것 확인, 잡다한 버그수정

선 약관동의 후 이메일/비번 입력, 파라미터 term_FL이름 변경(sql과 일치화), DB데이터 들어가는것 확인, 잡다한

---

src/main/java/com/livre/controller/book/InsertReviewController.java
src/main/java/com/livre/controller/book/MyReviewDetailController.java
src/main/java/com/livre/controller/book/MyReviewUpdateController.java
src/main/java/com/livre/model/bean/MyReview.java
src/main/java/com/livre/model/dao/MyReviewDao.java
src/main/java/com/livre/model/dao/MyReviewDao2.java
src/main/webapp/book/review-detail.jsp
src/main/webapp/book/review-upload.jsp
src/main/webapp/css/reivew-detail.css
src/main/webapp/css/reivew-upload.css

- MyReview Dao를 2개로 나눔(독후감 목록 / 상세보기 때문)
- 장르 값 넘기기 구현

독후감 수정 기능 구현 마무리

---

src/main/java/com/livre/controller/member/CelebrateController.java
src/main/java/com/livre/controller/member/MyPageController.java
src/main/java/com/livre/model/bean/Member.java
src/main/java/com/livre/model/dao/MemberDao.java

genreNo => genreList

---

src/main/java/com/livre/controller/member/CelebrateController.java
src/main/java/com/livre/model/dao/MemberDao.java
src/main/webapp/member/collectPreference.jsp
src/main/webapp/member/createNickname.jsp
src/main/webapp/member/finalCheck.jsp
src/main/webapp/member/selectGender.jsp

회원가입 기능 건너뛰기 가입, 상세정보 기입 후 가입 둘 다 구현 완료

회원가입 기능 건너뛰기 가입, 상세정보 기입 후 가입 둘 다 구현 완료

---

.settings/org.eclipse.core.resources.prefs
src/main/webapp/member/agreement.jsp
src/main/webapp/member/joinMemberShip.jsp

약관동의 완성 : checkAll 기능, Y,N값으로 파라미터 인풋으로 전송 기능 구현

약관동의 완성 : checkAll 기능, Y,N값으로 파라미터 인풋으로 전송 기능 구현

---

src/main/java/com/livre/controller/book/InsertReviewController.java
src/main/java/com/livre/controller/book/MyReviewDetailController.java
src/main/java/com/livre/controller/book/MyReviewUpdateController.java
src/main/java/com/livre/model/bean/MyReview.java
src/main/java/com/livre/model/dao/MyReviewDao.java
src/main/java/com/livre/model/dao/MyReviewDao2.java
src/main/webapp/book/my-review.jsp
src/main/webapp/book/review-detail.jsp
src/main/webapp/book/review-upload.jsp
src/main/webapp/common/common.jsp
src/main/webapp/css/my-review.css
src/main/webapp/css/reivew-detail.css
src/main/webapp/css/reivew-upload.css
src/main/webapp/index.jsp
src/main/webapp/js/review-upload.js

상세보기 안되는 것 수정

---

src/main/java/com/livre/common/SuperClass.java
src/main/webapp/book/bookList.jsp
src/main/webapp/book/my-review.jsp
src/main/webapp/common/common2.jsp
src/main/webapp/member/agreement.jsp
src/main/webapp/member/collectPreference.jsp
src/main/webapp/member/createNickname.jsp
src/main/webapp/member/finalCheck.jsp
src/main/webapp/member/joinMemberShip.jsp
src/main/webapp/member/selectGender.jsp

common2 메뉴 이동 하이라이트 css적용 기능

---

src/main/java/com/livre/controller/member/MemberInsertController.java
src/main/webapp/css/collectPreferenceStyle.css
src/main/webapp/css/joinMemberShipStyle.css
src/main/webapp/css/selectGenderStyle.css
src/main/webapp/member/agreement.jsp
src/main/webapp/member/collectPreference.jsp
src/main/webapp/member/createNickname.jsp
src/main/webapp/member/finalCheck.jsp
src/main/webapp/member/joinMemberShip.jsp
src/main/webapp/member/selectGender.jsp

sizing 제거, header 제거, 커서 포인터 주기

sizing 제거, header 제거, 커서 포인터 주기

---

src/main/java/com/livre/common/FrontController.java
src/main/java/com/livre/controller/member/ImgUpdateController.java
src/main/java/com/livre/controller/member/MyPageController.java
src/main/java/com/livre/model/dao/MemberDao.java
src/main/java/com/livre/utility/CustomFileRenamePolicy.java
src/main/java/com/livre/utility/MyUtility.java
src/main/webapp/css/my-page.css
src/main/webapp/member/ChangeProfileImg.jsp
src/main/webapp/member/my-page2.jsp

2024 02 19 jhk 커밋

---

src/main/java/com/livre/controller/member/ImgUpdateController.java
src/main/java/com/livre/controller/member/MemberDeleteController.java
src/main/java/com/livre/controller/member/MyPageController.java
src/main/java/com/livre/model/bean/Genres.java
src/main/java/com/livre/model/dao/MemberDao.java
src/main/java/com/livre/model/dao/SuperDao.java
src/main/webapp/WEB-INF/todolist.txt
src/main/webapp/member/ChangeProfileImg.jsp
src/main/webapp/member/my-page.jsp

마이페이지 북마크 기능 제외 전부 구현 완/ 2024 02 20 커밋 /

마이페이지 북마크 기능 제외 전부 구현 완/ 2024 02 20 커밋 /

---

src/main/webapp/common/common2.jsp
src/main/webapp/css/joinMemberShipStyle.css
src/main/webapp/member/joinMemberShip.jsp

css 잔잔바리 다듬기

---

src/main/webapp/WEB-INF/todolist.txt
src/main/webapp/css/main-page.css
src/main/webapp/css/my-page.css

2024/css 몇군데 추가

---

src/main/webapp/css/main-page.css

달력 왕건이 이미지 수정

---

src/main/webapp/js/createNicknameScript.js
src/main/webapp/member/celebrate.jsp

회원가입 -> 로그인페이지로 이동

---

src/main/java/com/livre/controller/member/MyFavoriteReviewController.java
src/main/java/com/livre/controller/member/MyPageController.java
src/main/java/com/livre/model/dao/MemberDao.java
src/main/webapp/WEB-INF/todolist.txt
src/main/webapp/common/common2.jsp
src/main/webapp/common/common3.jsp
src/main/webapp/css/header.css
src/main/webapp/member/my-favorite-review.jsp
src/main/webapp/member/my-page.jsp

common2,3에 헤더 이미지 추가 및 css 헤더 이미지 추가 my-favorite-review 추가 css 미완
